version: "3"
services:
  # ==================================================================================

  # A. Database Setup

  # ==================================================================================

  PostgresDbs:
    container_name: PostgresDbs
    image: postgres
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_MULTIPLE_DATABASES: songdb, egodb
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    ports:
      - "5051:80"

  # ==================================================================================

  # B. Object Storage

  # ==================================================================================

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://host.docker.internal:9000 minio minio123;
      /usr/bin/mc mb myminio/state;
      /usr/bin/mc mb myminio/object;
      exit 0;
      "

  # ==================================================================================

  # Misc. Persistent volumes

  # ==================================================================================

volumes:
  minio-data:
